// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/project/project.proto

package project

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectService_CreateProject_FullMethodName      = "/project.ProjectService/CreateProject"
	ProjectService_GetProject_FullMethodName         = "/project.ProjectService/GetProject"
	ProjectService_UpdateProject_FullMethodName      = "/project.ProjectService/UpdateProject"
	ProjectService_DeleteProject_FullMethodName      = "/project.ProjectService/DeleteProject"
	ProjectService_ListProjects_FullMethodName       = "/project.ProjectService/ListProjects"
	ProjectService_CreateSkill_FullMethodName        = "/project.ProjectService/CreateSkill"
	ProjectService_ListSkills_FullMethodName         = "/project.ProjectService/ListSkills"
	ProjectService_AddProjectSkill_FullMethodName    = "/project.ProjectService/AddProjectSkill"
	ProjectService_RemoveProjectSkill_FullMethodName = "/project.ProjectService/RemoveProjectSkill"
	ProjectService_AddProjectTech_FullMethodName     = "/project.ProjectService/AddProjectTech"
	ProjectService_RemoveProjectTech_FullMethodName  = "/project.ProjectService/RemoveProjectTech"
	ProjectService_AddProjectImage_FullMethodName    = "/project.ProjectService/AddProjectImage"
	ProjectService_RemoveProjectImage_FullMethodName = "/project.ProjectService/RemoveProjectImage"
	ProjectService_ListProjectImages_FullMethodName  = "/project.ProjectService/ListProjectImages"
	ProjectService_AddProjectLink_FullMethodName     = "/project.ProjectService/AddProjectLink"
	ProjectService_RemoveProjectLink_FullMethodName  = "/project.ProjectService/RemoveProjectLink"
	ProjectService_ListProjectLinks_FullMethodName   = "/project.ProjectService/ListProjectLinks"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Project Service
type ProjectServiceClient interface {
	// Project CRUD
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*Empty, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	// Skills
	CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...grpc.CallOption) (*SkillResponse, error)
	ListSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	AddProjectSkill(ctx context.Context, in *AddProjectSkillRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveProjectSkill(ctx context.Context, in *RemoveProjectSkillRequest, opts ...grpc.CallOption) (*Empty, error)
	// Tech Stack
	AddProjectTech(ctx context.Context, in *AddProjectTechRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveProjectTech(ctx context.Context, in *RemoveProjectTechRequest, opts ...grpc.CallOption) (*Empty, error)
	// Images
	AddProjectImage(ctx context.Context, in *AddProjectImageRequest, opts ...grpc.CallOption) (*ProjectImageResponse, error)
	RemoveProjectImage(ctx context.Context, in *RemoveProjectImageRequest, opts ...grpc.CallOption) (*Empty, error)
	ListProjectImages(ctx context.Context, in *ListProjectImagesRequest, opts ...grpc.CallOption) (*ListProjectImagesResponse, error)
	// Links
	AddProjectLink(ctx context.Context, in *AddProjectLinkRequest, opts ...grpc.CallOption) (*ProjectLinkResponse, error)
	RemoveProjectLink(ctx context.Context, in *RemoveProjectLinkRequest, opts ...grpc.CallOption) (*Empty, error)
	ListProjectLinks(ctx context.Context, in *ListProjectLinksRequest, opts ...grpc.CallOption) (*ListProjectLinksResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, ProjectService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...grpc.CallOption) (*SkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillResponse)
	err := c.cc.Invoke(ctx, ProjectService_CreateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, ProjectService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AddProjectSkill(ctx context.Context, in *AddProjectSkillRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectService_AddProjectSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RemoveProjectSkill(ctx context.Context, in *RemoveProjectSkillRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectService_RemoveProjectSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AddProjectTech(ctx context.Context, in *AddProjectTechRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectService_AddProjectTech_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RemoveProjectTech(ctx context.Context, in *RemoveProjectTechRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectService_RemoveProjectTech_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AddProjectImage(ctx context.Context, in *AddProjectImageRequest, opts ...grpc.CallOption) (*ProjectImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectImageResponse)
	err := c.cc.Invoke(ctx, ProjectService_AddProjectImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RemoveProjectImage(ctx context.Context, in *RemoveProjectImageRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectService_RemoveProjectImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListProjectImages(ctx context.Context, in *ListProjectImagesRequest, opts ...grpc.CallOption) (*ListProjectImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectImagesResponse)
	err := c.cc.Invoke(ctx, ProjectService_ListProjectImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AddProjectLink(ctx context.Context, in *AddProjectLinkRequest, opts ...grpc.CallOption) (*ProjectLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectLinkResponse)
	err := c.cc.Invoke(ctx, ProjectService_AddProjectLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RemoveProjectLink(ctx context.Context, in *RemoveProjectLinkRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectService_RemoveProjectLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListProjectLinks(ctx context.Context, in *ListProjectLinksRequest, opts ...grpc.CallOption) (*ListProjectLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectLinksResponse)
	err := c.cc.Invoke(ctx, ProjectService_ListProjectLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility.
//
// Project Service
type ProjectServiceServer interface {
	// Project CRUD
	CreateProject(context.Context, *CreateProjectRequest) (*ProjectResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*ProjectResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*Empty, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	// Skills
	CreateSkill(context.Context, *CreateSkillRequest) (*SkillResponse, error)
	ListSkills(context.Context, *Empty) (*ListSkillsResponse, error)
	AddProjectSkill(context.Context, *AddProjectSkillRequest) (*Empty, error)
	RemoveProjectSkill(context.Context, *RemoveProjectSkillRequest) (*Empty, error)
	// Tech Stack
	AddProjectTech(context.Context, *AddProjectTechRequest) (*Empty, error)
	RemoveProjectTech(context.Context, *RemoveProjectTechRequest) (*Empty, error)
	// Images
	AddProjectImage(context.Context, *AddProjectImageRequest) (*ProjectImageResponse, error)
	RemoveProjectImage(context.Context, *RemoveProjectImageRequest) (*Empty, error)
	ListProjectImages(context.Context, *ListProjectImagesRequest) (*ListProjectImagesResponse, error)
	// Links
	AddProjectLink(context.Context, *AddProjectLinkRequest) (*ProjectLinkResponse, error)
	RemoveProjectLink(context.Context, *RemoveProjectLinkRequest) (*Empty, error)
	ListProjectLinks(context.Context, *ListProjectLinksRequest) (*ListProjectLinksResponse, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceServer struct{}

func (UnimplementedProjectServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProject(context.Context, *GetProjectRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedProjectServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedProjectServiceServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedProjectServiceServer) CreateSkill(context.Context, *CreateSkillRequest) (*SkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSkill not implemented")
}
func (UnimplementedProjectServiceServer) ListSkills(context.Context, *Empty) (*ListSkillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedProjectServiceServer) AddProjectSkill(context.Context, *AddProjectSkillRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectSkill not implemented")
}
func (UnimplementedProjectServiceServer) RemoveProjectSkill(context.Context, *RemoveProjectSkillRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProjectSkill not implemented")
}
func (UnimplementedProjectServiceServer) AddProjectTech(context.Context, *AddProjectTechRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectTech not implemented")
}
func (UnimplementedProjectServiceServer) RemoveProjectTech(context.Context, *RemoveProjectTechRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProjectTech not implemented")
}
func (UnimplementedProjectServiceServer) AddProjectImage(context.Context, *AddProjectImageRequest) (*ProjectImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectImage not implemented")
}
func (UnimplementedProjectServiceServer) RemoveProjectImage(context.Context, *RemoveProjectImageRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProjectImage not implemented")
}
func (UnimplementedProjectServiceServer) ListProjectImages(context.Context, *ListProjectImagesRequest) (*ListProjectImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjectImages not implemented")
}
func (UnimplementedProjectServiceServer) AddProjectLink(context.Context, *AddProjectLinkRequest) (*ProjectLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectLink not implemented")
}
func (UnimplementedProjectServiceServer) RemoveProjectLink(context.Context, *RemoveProjectLinkRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProjectLink not implemented")
}
func (UnimplementedProjectServiceServer) ListProjectLinks(context.Context, *ListProjectLinksRequest) (*ListProjectLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjectLinks not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}
func (UnimplementedProjectServiceServer) testEmbeddedByValue()                        {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CreateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CreateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateSkill(ctx, req.(*CreateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListSkills(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AddProjectSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AddProjectSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AddProjectSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AddProjectSkill(ctx, req.(*AddProjectSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RemoveProjectSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProjectSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RemoveProjectSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RemoveProjectSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RemoveProjectSkill(ctx, req.(*RemoveProjectSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AddProjectTech_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectTechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AddProjectTech(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AddProjectTech_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AddProjectTech(ctx, req.(*AddProjectTechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RemoveProjectTech_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProjectTechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RemoveProjectTech(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RemoveProjectTech_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RemoveProjectTech(ctx, req.(*RemoveProjectTechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AddProjectImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AddProjectImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AddProjectImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AddProjectImage(ctx, req.(*AddProjectImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RemoveProjectImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProjectImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RemoveProjectImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RemoveProjectImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RemoveProjectImage(ctx, req.(*RemoveProjectImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListProjectImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProjectImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListProjectImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProjectImages(ctx, req.(*ListProjectImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AddProjectLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AddProjectLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AddProjectLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AddProjectLink(ctx, req.(*AddProjectLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RemoveProjectLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProjectLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RemoveProjectLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RemoveProjectLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RemoveProjectLink(ctx, req.(*RemoveProjectLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListProjectLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProjectLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListProjectLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProjectLinks(ctx, req.(*ListProjectLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _ProjectService_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ProjectService_GetProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ProjectService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ProjectService_DeleteProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _ProjectService_ListProjects_Handler,
		},
		{
			MethodName: "CreateSkill",
			Handler:    _ProjectService_CreateSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _ProjectService_ListSkills_Handler,
		},
		{
			MethodName: "AddProjectSkill",
			Handler:    _ProjectService_AddProjectSkill_Handler,
		},
		{
			MethodName: "RemoveProjectSkill",
			Handler:    _ProjectService_RemoveProjectSkill_Handler,
		},
		{
			MethodName: "AddProjectTech",
			Handler:    _ProjectService_AddProjectTech_Handler,
		},
		{
			MethodName: "RemoveProjectTech",
			Handler:    _ProjectService_RemoveProjectTech_Handler,
		},
		{
			MethodName: "AddProjectImage",
			Handler:    _ProjectService_AddProjectImage_Handler,
		},
		{
			MethodName: "RemoveProjectImage",
			Handler:    _ProjectService_RemoveProjectImage_Handler,
		},
		{
			MethodName: "ListProjectImages",
			Handler:    _ProjectService_ListProjectImages_Handler,
		},
		{
			MethodName: "AddProjectLink",
			Handler:    _ProjectService_AddProjectLink_Handler,
		},
		{
			MethodName: "RemoveProjectLink",
			Handler:    _ProjectService_RemoveProjectLink_Handler,
		},
		{
			MethodName: "ListProjectLinks",
			Handler:    _ProjectService_ListProjectLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/project/project.proto",
}
