// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/project/project.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_project_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{0}
}

// Project messages
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Skills        []*Skill               `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
	TechStack     []string               `protobuf:"bytes,8,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`
	Images        []*ProjectImage        `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`
	Links         []*ProjectLink         `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_project_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Project) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Project) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *Project) GetImages() []*ProjectImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Project) GetLinks() []*ProjectLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_proto_project_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateProjectRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *CreateProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_proto_project_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_proto_project_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_proto_project_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProjectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateProjectRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *UpdateProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_proto_project_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProjectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_proto_project_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{7}
}

func (x *ListProjectsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProjectsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_proto_project_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{8}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Skill messages
type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_proto_project_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{9}
}

func (x *Skill) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillRequest) Reset() {
	*x = CreateSkillRequest{}
	mi := &file_proto_project_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequest) ProtoMessage() {}

func (x *CreateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillResponse) Reset() {
	*x = SkillResponse{}
	mi := &file_proto_project_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillResponse) ProtoMessage() {}

func (x *SkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillResponse.ProtoReflect.Descriptor instead.
func (*SkillResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{11}
}

func (x *SkillResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_proto_project_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{12}
}

func (x *ListSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type AddProjectSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SkillId       int64                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectSkillRequest) Reset() {
	*x = AddProjectSkillRequest{}
	mi := &file_proto_project_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectSkillRequest) ProtoMessage() {}

func (x *AddProjectSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectSkillRequest.ProtoReflect.Descriptor instead.
func (*AddProjectSkillRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{13}
}

func (x *AddProjectSkillRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AddProjectSkillRequest) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

type RemoveProjectSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SkillId       int64                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectSkillRequest) Reset() {
	*x = RemoveProjectSkillRequest{}
	mi := &file_proto_project_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectSkillRequest) ProtoMessage() {}

func (x *RemoveProjectSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectSkillRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectSkillRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveProjectSkillRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *RemoveProjectSkillRequest) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

// Tech Stack messages
type AddProjectTechRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TechName      string                 `protobuf:"bytes,2,opt,name=tech_name,json=techName,proto3" json:"tech_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectTechRequest) Reset() {
	*x = AddProjectTechRequest{}
	mi := &file_proto_project_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectTechRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectTechRequest) ProtoMessage() {}

func (x *AddProjectTechRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectTechRequest.ProtoReflect.Descriptor instead.
func (*AddProjectTechRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{15}
}

func (x *AddProjectTechRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AddProjectTechRequest) GetTechName() string {
	if x != nil {
		return x.TechName
	}
	return ""
}

type RemoveProjectTechRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TechName      string                 `protobuf:"bytes,2,opt,name=tech_name,json=techName,proto3" json:"tech_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectTechRequest) Reset() {
	*x = RemoveProjectTechRequest{}
	mi := &file_proto_project_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectTechRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectTechRequest) ProtoMessage() {}

func (x *RemoveProjectTechRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectTechRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectTechRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveProjectTechRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *RemoveProjectTechRequest) GetTechName() string {
	if x != nil {
		return x.TechName
	}
	return ""
}

// Image messages
type ProjectImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectImage) Reset() {
	*x = ProjectImage{}
	mi := &file_proto_project_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectImage) ProtoMessage() {}

func (x *ProjectImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectImage.ProtoReflect.Descriptor instead.
func (*ProjectImage) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{17}
}

func (x *ProjectImage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectImage) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectImage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProjectImage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectImage) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

type AddProjectImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectImageRequest) Reset() {
	*x = AddProjectImageRequest{}
	mi := &file_proto_project_project_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectImageRequest) ProtoMessage() {}

func (x *AddProjectImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectImageRequest.ProtoReflect.Descriptor instead.
func (*AddProjectImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{18}
}

func (x *AddProjectImageRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AddProjectImageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *AddProjectImageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ProjectImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ProjectImage          `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectImageResponse) Reset() {
	*x = ProjectImageResponse{}
	mi := &file_proto_project_project_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectImageResponse) ProtoMessage() {}

func (x *ProjectImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectImageResponse.ProtoReflect.Descriptor instead.
func (*ProjectImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{19}
}

func (x *ProjectImageResponse) GetImage() *ProjectImage {
	if x != nil {
		return x.Image
	}
	return nil
}

type RemoveProjectImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectImageRequest) Reset() {
	*x = RemoveProjectImageRequest{}
	mi := &file_proto_project_project_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectImageRequest) ProtoMessage() {}

func (x *RemoveProjectImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveProjectImageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListProjectImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectImagesRequest) Reset() {
	*x = ListProjectImagesRequest{}
	mi := &file_proto_project_project_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectImagesRequest) ProtoMessage() {}

func (x *ListProjectImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectImagesRequest.ProtoReflect.Descriptor instead.
func (*ListProjectImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{21}
}

func (x *ListProjectImagesRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type ListProjectImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ProjectImage        `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectImagesResponse) Reset() {
	*x = ListProjectImagesResponse{}
	mi := &file_proto_project_project_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectImagesResponse) ProtoMessage() {}

func (x *ListProjectImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectImagesResponse.ProtoReflect.Descriptor instead.
func (*ListProjectImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{22}
}

func (x *ListProjectImagesResponse) GetImages() []*ProjectImage {
	if x != nil {
		return x.Images
	}
	return nil
}

// Link messages
type ProjectLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	LinkUrl       string                 `protobuf:"bytes,3,opt,name=link_url,json=linkUrl,proto3" json:"link_url,omitempty"`
	LinkType      string                 `protobuf:"bytes,4,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"` // github, live, document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectLink) Reset() {
	*x = ProjectLink{}
	mi := &file_proto_project_project_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectLink) ProtoMessage() {}

func (x *ProjectLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectLink.ProtoReflect.Descriptor instead.
func (*ProjectLink) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{23}
}

func (x *ProjectLink) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectLink) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectLink) GetLinkUrl() string {
	if x != nil {
		return x.LinkUrl
	}
	return ""
}

func (x *ProjectLink) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

type AddProjectLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	LinkUrl       string                 `protobuf:"bytes,2,opt,name=link_url,json=linkUrl,proto3" json:"link_url,omitempty"`
	LinkType      string                 `protobuf:"bytes,3,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectLinkRequest) Reset() {
	*x = AddProjectLinkRequest{}
	mi := &file_proto_project_project_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectLinkRequest) ProtoMessage() {}

func (x *AddProjectLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectLinkRequest.ProtoReflect.Descriptor instead.
func (*AddProjectLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{24}
}

func (x *AddProjectLinkRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AddProjectLinkRequest) GetLinkUrl() string {
	if x != nil {
		return x.LinkUrl
	}
	return ""
}

func (x *AddProjectLinkRequest) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

type ProjectLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ProjectLink           `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectLinkResponse) Reset() {
	*x = ProjectLinkResponse{}
	mi := &file_proto_project_project_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectLinkResponse) ProtoMessage() {}

func (x *ProjectLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectLinkResponse.ProtoReflect.Descriptor instead.
func (*ProjectLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{25}
}

func (x *ProjectLinkResponse) GetLink() *ProjectLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type RemoveProjectLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectLinkRequest) Reset() {
	*x = RemoveProjectLinkRequest{}
	mi := &file_proto_project_project_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectLinkRequest) ProtoMessage() {}

func (x *RemoveProjectLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectLinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveProjectLinkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListProjectLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectLinksRequest) Reset() {
	*x = ListProjectLinksRequest{}
	mi := &file_proto_project_project_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectLinksRequest) ProtoMessage() {}

func (x *ListProjectLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectLinksRequest.ProtoReflect.Descriptor instead.
func (*ListProjectLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{27}
}

func (x *ListProjectLinksRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type ListProjectLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*ProjectLink         `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectLinksResponse) Reset() {
	*x = ListProjectLinksResponse{}
	mi := &file_proto_project_project_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectLinksResponse) ProtoMessage() {}

func (x *ListProjectLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectLinksResponse.ProtoReflect.Descriptor instead.
func (*ListProjectLinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{28}
}

func (x *ListProjectLinksResponse) GetLinks() []*ProjectLink {
	if x != nil {
		return x.Links
	}
	return nil
}

var File_proto_project_project_proto protoreflect.FileDescriptor

const file_proto_project_project_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/project/project.proto\x12\aproject\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xf1\x03\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12&\n" +
	"\x06skills\x18\a \x03(\v2\x0e.project.SkillR\x06skills\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\b \x03(\tR\ttechStack\x12-\n" +
	"\x06images\x18\t \x03(\v2\x15.project.ProjectImageR\x06images\x12*\n" +
	"\x05links\x18\n" +
	" \x03(\v2\x14.project.ProjectLinkR\x05links\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd6\x01\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x0fProjectResponse\x12*\n" +
	"\aproject\x18\x01 \x01(\v2\x10.project.ProjectR\aproject\"\xe6\x01\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"&\n" +
	"\x14DeleteProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"W\n" +
	"\x13ListProjectsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"Z\n" +
	"\x14ListProjectsResponse\x12,\n" +
	"\bprojects\x18\x01 \x03(\v2\x10.project.ProjectR\bprojects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"+\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\x12CreateSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\rSkillResponse\x12$\n" +
	"\x05skill\x18\x01 \x01(\v2\x0e.project.SkillR\x05skill\"<\n" +
	"\x12ListSkillsResponse\x12&\n" +
	"\x06skills\x18\x01 \x03(\v2\x0e.project.SkillR\x06skills\"R\n" +
	"\x16AddProjectSkillRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x03R\askillId\"U\n" +
	"\x19RemoveProjectSkillRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x03R\askillId\"S\n" +
	"\x15AddProjectTechRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x1b\n" +
	"\ttech_name\x18\x02 \x01(\tR\btechName\"V\n" +
	"\x18RemoveProjectTechRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x1b\n" +
	"\ttech_name\x18\x02 \x01(\tR\btechName\"\xb9\x01\n" +
	"\fProjectImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\vuploaded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"v\n" +
	"\x16AddProjectImageRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"C\n" +
	"\x14ProjectImageResponse\x12+\n" +
	"\x05image\x18\x01 \x01(\v2\x15.project.ProjectImageR\x05image\"+\n" +
	"\x19RemoveProjectImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"9\n" +
	"\x18ListProjectImagesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\"J\n" +
	"\x19ListProjectImagesResponse\x12-\n" +
	"\x06images\x18\x01 \x03(\v2\x15.project.ProjectImageR\x06images\"t\n" +
	"\vProjectLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x19\n" +
	"\blink_url\x18\x03 \x01(\tR\alinkUrl\x12\x1b\n" +
	"\tlink_type\x18\x04 \x01(\tR\blinkType\"n\n" +
	"\x15AddProjectLinkRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x19\n" +
	"\blink_url\x18\x02 \x01(\tR\alinkUrl\x12\x1b\n" +
	"\tlink_type\x18\x03 \x01(\tR\blinkType\"?\n" +
	"\x13ProjectLinkResponse\x12(\n" +
	"\x04link\x18\x01 \x01(\v2\x14.project.ProjectLinkR\x04link\"*\n" +
	"\x18RemoveProjectLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x17ListProjectLinksRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\"F\n" +
	"\x18ListProjectLinksResponse\x12*\n" +
	"\x05links\x18\x01 \x03(\v2\x14.project.ProjectLinkR\x05links2\xf6\t\n" +
	"\x0eProjectService\x12H\n" +
	"\rCreateProject\x12\x1d.project.CreateProjectRequest\x1a\x18.project.ProjectResponse\x12B\n" +
	"\n" +
	"GetProject\x12\x1a.project.GetProjectRequest\x1a\x18.project.ProjectResponse\x12H\n" +
	"\rUpdateProject\x12\x1d.project.UpdateProjectRequest\x1a\x18.project.ProjectResponse\x12>\n" +
	"\rDeleteProject\x12\x1d.project.DeleteProjectRequest\x1a\x0e.project.Empty\x12K\n" +
	"\fListProjects\x12\x1c.project.ListProjectsRequest\x1a\x1d.project.ListProjectsResponse\x12B\n" +
	"\vCreateSkill\x12\x1b.project.CreateSkillRequest\x1a\x16.project.SkillResponse\x129\n" +
	"\n" +
	"ListSkills\x12\x0e.project.Empty\x1a\x1b.project.ListSkillsResponse\x12B\n" +
	"\x0fAddProjectSkill\x12\x1f.project.AddProjectSkillRequest\x1a\x0e.project.Empty\x12H\n" +
	"\x12RemoveProjectSkill\x12\".project.RemoveProjectSkillRequest\x1a\x0e.project.Empty\x12@\n" +
	"\x0eAddProjectTech\x12\x1e.project.AddProjectTechRequest\x1a\x0e.project.Empty\x12F\n" +
	"\x11RemoveProjectTech\x12!.project.RemoveProjectTechRequest\x1a\x0e.project.Empty\x12Q\n" +
	"\x0fAddProjectImage\x12\x1f.project.AddProjectImageRequest\x1a\x1d.project.ProjectImageResponse\x12H\n" +
	"\x12RemoveProjectImage\x12\".project.RemoveProjectImageRequest\x1a\x0e.project.Empty\x12Z\n" +
	"\x11ListProjectImages\x12!.project.ListProjectImagesRequest\x1a\".project.ListProjectImagesResponse\x12N\n" +
	"\x0eAddProjectLink\x12\x1e.project.AddProjectLinkRequest\x1a\x1c.project.ProjectLinkResponse\x12F\n" +
	"\x11RemoveProjectLink\x12!.project.RemoveProjectLinkRequest\x1a\x0e.project.Empty\x12W\n" +
	"\x10ListProjectLinks\x12 .project.ListProjectLinksRequest\x1a!.project.ListProjectLinksResponseB$Z\"github.com/portfolio/proto/projectb\x06proto3"

var (
	file_proto_project_project_proto_rawDescOnce sync.Once
	file_proto_project_project_proto_rawDescData []byte
)

func file_proto_project_project_proto_rawDescGZIP() []byte {
	file_proto_project_project_proto_rawDescOnce.Do(func() {
		file_proto_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_project_project_proto_rawDesc), len(file_proto_project_project_proto_rawDesc)))
	})
	return file_proto_project_project_proto_rawDescData
}

var file_proto_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_project_project_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: project.Empty
	(*Project)(nil),                   // 1: project.Project
	(*CreateProjectRequest)(nil),      // 2: project.CreateProjectRequest
	(*GetProjectRequest)(nil),         // 3: project.GetProjectRequest
	(*ProjectResponse)(nil),           // 4: project.ProjectResponse
	(*UpdateProjectRequest)(nil),      // 5: project.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),      // 6: project.DeleteProjectRequest
	(*ListProjectsRequest)(nil),       // 7: project.ListProjectsRequest
	(*ListProjectsResponse)(nil),      // 8: project.ListProjectsResponse
	(*Skill)(nil),                     // 9: project.Skill
	(*CreateSkillRequest)(nil),        // 10: project.CreateSkillRequest
	(*SkillResponse)(nil),             // 11: project.SkillResponse
	(*ListSkillsResponse)(nil),        // 12: project.ListSkillsResponse
	(*AddProjectSkillRequest)(nil),    // 13: project.AddProjectSkillRequest
	(*RemoveProjectSkillRequest)(nil), // 14: project.RemoveProjectSkillRequest
	(*AddProjectTechRequest)(nil),     // 15: project.AddProjectTechRequest
	(*RemoveProjectTechRequest)(nil),  // 16: project.RemoveProjectTechRequest
	(*ProjectImage)(nil),              // 17: project.ProjectImage
	(*AddProjectImageRequest)(nil),    // 18: project.AddProjectImageRequest
	(*ProjectImageResponse)(nil),      // 19: project.ProjectImageResponse
	(*RemoveProjectImageRequest)(nil), // 20: project.RemoveProjectImageRequest
	(*ListProjectImagesRequest)(nil),  // 21: project.ListProjectImagesRequest
	(*ListProjectImagesResponse)(nil), // 22: project.ListProjectImagesResponse
	(*ProjectLink)(nil),               // 23: project.ProjectLink
	(*AddProjectLinkRequest)(nil),     // 24: project.AddProjectLinkRequest
	(*ProjectLinkResponse)(nil),       // 25: project.ProjectLinkResponse
	(*RemoveProjectLinkRequest)(nil),  // 26: project.RemoveProjectLinkRequest
	(*ListProjectLinksRequest)(nil),   // 27: project.ListProjectLinksRequest
	(*ListProjectLinksResponse)(nil),  // 28: project.ListProjectLinksResponse
	(*timestamppb.Timestamp)(nil),     // 29: google.protobuf.Timestamp
}
var file_proto_project_project_proto_depIdxs = []int32{
	29, // 0: project.Project.start_date:type_name -> google.protobuf.Timestamp
	29, // 1: project.Project.end_date:type_name -> google.protobuf.Timestamp
	9,  // 2: project.Project.skills:type_name -> project.Skill
	17, // 3: project.Project.images:type_name -> project.ProjectImage
	23, // 4: project.Project.links:type_name -> project.ProjectLink
	29, // 5: project.Project.created_at:type_name -> google.protobuf.Timestamp
	29, // 6: project.Project.updated_at:type_name -> google.protobuf.Timestamp
	29, // 7: project.CreateProjectRequest.start_date:type_name -> google.protobuf.Timestamp
	29, // 8: project.CreateProjectRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 9: project.ProjectResponse.project:type_name -> project.Project
	29, // 10: project.UpdateProjectRequest.start_date:type_name -> google.protobuf.Timestamp
	29, // 11: project.UpdateProjectRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 12: project.ListProjectsResponse.projects:type_name -> project.Project
	9,  // 13: project.SkillResponse.skill:type_name -> project.Skill
	9,  // 14: project.ListSkillsResponse.skills:type_name -> project.Skill
	29, // 15: project.ProjectImage.uploaded_at:type_name -> google.protobuf.Timestamp
	17, // 16: project.ProjectImageResponse.image:type_name -> project.ProjectImage
	17, // 17: project.ListProjectImagesResponse.images:type_name -> project.ProjectImage
	23, // 18: project.ProjectLinkResponse.link:type_name -> project.ProjectLink
	23, // 19: project.ListProjectLinksResponse.links:type_name -> project.ProjectLink
	2,  // 20: project.ProjectService.CreateProject:input_type -> project.CreateProjectRequest
	3,  // 21: project.ProjectService.GetProject:input_type -> project.GetProjectRequest
	5,  // 22: project.ProjectService.UpdateProject:input_type -> project.UpdateProjectRequest
	6,  // 23: project.ProjectService.DeleteProject:input_type -> project.DeleteProjectRequest
	7,  // 24: project.ProjectService.ListProjects:input_type -> project.ListProjectsRequest
	10, // 25: project.ProjectService.CreateSkill:input_type -> project.CreateSkillRequest
	0,  // 26: project.ProjectService.ListSkills:input_type -> project.Empty
	13, // 27: project.ProjectService.AddProjectSkill:input_type -> project.AddProjectSkillRequest
	14, // 28: project.ProjectService.RemoveProjectSkill:input_type -> project.RemoveProjectSkillRequest
	15, // 29: project.ProjectService.AddProjectTech:input_type -> project.AddProjectTechRequest
	16, // 30: project.ProjectService.RemoveProjectTech:input_type -> project.RemoveProjectTechRequest
	18, // 31: project.ProjectService.AddProjectImage:input_type -> project.AddProjectImageRequest
	20, // 32: project.ProjectService.RemoveProjectImage:input_type -> project.RemoveProjectImageRequest
	21, // 33: project.ProjectService.ListProjectImages:input_type -> project.ListProjectImagesRequest
	24, // 34: project.ProjectService.AddProjectLink:input_type -> project.AddProjectLinkRequest
	26, // 35: project.ProjectService.RemoveProjectLink:input_type -> project.RemoveProjectLinkRequest
	27, // 36: project.ProjectService.ListProjectLinks:input_type -> project.ListProjectLinksRequest
	4,  // 37: project.ProjectService.CreateProject:output_type -> project.ProjectResponse
	4,  // 38: project.ProjectService.GetProject:output_type -> project.ProjectResponse
	4,  // 39: project.ProjectService.UpdateProject:output_type -> project.ProjectResponse
	0,  // 40: project.ProjectService.DeleteProject:output_type -> project.Empty
	8,  // 41: project.ProjectService.ListProjects:output_type -> project.ListProjectsResponse
	11, // 42: project.ProjectService.CreateSkill:output_type -> project.SkillResponse
	12, // 43: project.ProjectService.ListSkills:output_type -> project.ListSkillsResponse
	0,  // 44: project.ProjectService.AddProjectSkill:output_type -> project.Empty
	0,  // 45: project.ProjectService.RemoveProjectSkill:output_type -> project.Empty
	0,  // 46: project.ProjectService.AddProjectTech:output_type -> project.Empty
	0,  // 47: project.ProjectService.RemoveProjectTech:output_type -> project.Empty
	19, // 48: project.ProjectService.AddProjectImage:output_type -> project.ProjectImageResponse
	0,  // 49: project.ProjectService.RemoveProjectImage:output_type -> project.Empty
	22, // 50: project.ProjectService.ListProjectImages:output_type -> project.ListProjectImagesResponse
	25, // 51: project.ProjectService.AddProjectLink:output_type -> project.ProjectLinkResponse
	0,  // 52: project.ProjectService.RemoveProjectLink:output_type -> project.Empty
	28, // 53: project.ProjectService.ListProjectLinks:output_type -> project.ListProjectLinksResponse
	37, // [37:54] is the sub-list for method output_type
	20, // [20:37] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_project_project_proto_init() }
func file_proto_project_project_proto_init() {
	if File_proto_project_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_project_project_proto_rawDesc), len(file_proto_project_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_project_project_proto_goTypes,
		DependencyIndexes: file_proto_project_project_proto_depIdxs,
		MessageInfos:      file_proto_project_project_proto_msgTypes,
	}.Build()
	File_proto_project_project_proto = out.File
	file_proto_project_project_proto_goTypes = nil
	file_proto_project_project_proto_depIdxs = nil
}
