// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

// Project View messages
type ProjectView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViewedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=viewed_at,json=viewedAt,proto3" json:"viewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectView) Reset() {
	*x = ProjectView{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectView) ProtoMessage() {}

func (x *ProjectView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectView.ProtoReflect.Descriptor instead.
func (*ProjectView) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectView) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectView) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectView) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProjectView) GetViewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ViewedAt
	}
	return nil
}

type RecordProjectViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordProjectViewRequest) Reset() {
	*x = RecordProjectViewRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordProjectViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordProjectViewRequest) ProtoMessage() {}

func (x *RecordProjectViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordProjectViewRequest.ProtoReflect.Descriptor instead.
func (*RecordProjectViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *RecordProjectViewRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *RecordProjectViewRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProjectViewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectViewsRequest) Reset() {
	*x = GetProjectViewsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectViewsRequest) ProtoMessage() {}

func (x *GetProjectViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectViewsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectViewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectViewsRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *GetProjectViewsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetProjectViewsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ProjectViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*ProjectView         `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	TotalViews    int32                  `protobuf:"varint,2,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectViewsResponse) Reset() {
	*x = ProjectViewsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectViewsResponse) ProtoMessage() {}

func (x *ProjectViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectViewsResponse.ProtoReflect.Descriptor instead.
func (*ProjectViewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectViewsResponse) GetViews() []*ProjectView {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *ProjectViewsResponse) GetTotalViews() int32 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

// Task Activity messages
type TaskActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // created, updated, completed
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskActivity) Reset() {
	*x = TaskActivity{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActivity) ProtoMessage() {}

func (x *TaskActivity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActivity.ProtoReflect.Descriptor instead.
func (*TaskActivity) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *TaskActivity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskActivity) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskActivity) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TaskActivity) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TaskActivity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RecordTaskActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTaskActivityRequest) Reset() {
	*x = RecordTaskActivityRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTaskActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTaskActivityRequest) ProtoMessage() {}

func (x *RecordTaskActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTaskActivityRequest.ProtoReflect.Descriptor instead.
func (*RecordTaskActivityRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *RecordTaskActivityRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RecordTaskActivityRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecordTaskActivityRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type GetTaskActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // optional: get all activities for a project
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskActivitiesRequest) Reset() {
	*x = GetTaskActivitiesRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskActivitiesRequest) ProtoMessage() {}

func (x *GetTaskActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetTaskActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskActivitiesRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskActivitiesRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type TaskActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*TaskActivity        `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskActivitiesResponse) Reset() {
	*x = TaskActivitiesResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActivitiesResponse) ProtoMessage() {}

func (x *TaskActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActivitiesResponse.ProtoReflect.Descriptor instead.
func (*TaskActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *TaskActivitiesResponse) GetActivities() []*TaskActivity {
	if x != nil {
		return x.Activities
	}
	return nil
}

// Project Stats messages
type ProjectStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TotalTasks      int32                  `protobuf:"varint,2,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks  int32                  `protobuf:"varint,3,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	ProgressPercent float64                `protobuf:"fixed64,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	LastUpdated     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectStats) Reset() {
	*x = ProjectStats{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectStats) ProtoMessage() {}

func (x *ProjectStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectStats.ProtoReflect.Descriptor instead.
func (*ProjectStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectStats) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectStats) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *ProjectStats) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *ProjectStats) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *ProjectStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type GetProjectStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectStatsRequest) Reset() {
	*x = GetProjectStatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectStatsRequest) ProtoMessage() {}

func (x *GetProjectStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectStatsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetProjectStatsRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type ProjectStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *ProjectStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectStatsResponse) Reset() {
	*x = ProjectStatsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectStatsResponse) ProtoMessage() {}

func (x *ProjectStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectStatsResponse.ProtoReflect.Descriptor instead.
func (*ProjectStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectStatsResponse) GetStats() *ProjectStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UpdateProjectStatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TotalTasks     int64                  `protobuf:"varint,2,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks int64                  `protobuf:"varint,3,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProjectStatsRequest) Reset() {
	*x = UpdateProjectStatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectStatsRequest) ProtoMessage() {}

func (x *UpdateProjectStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectStatsRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProjectStatsRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *UpdateProjectStatsRequest) GetTotalTasks() int64 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *UpdateProjectStatsRequest) GetCompletedTasks() int64 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

// Dashboard Stats messages
type GetDashboardStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // optional: filter by user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardStatsRequest) Reset() {
	*x = GetDashboardStatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsRequest) ProtoMessage() {}

func (x *GetDashboardStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *GetDashboardStatsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DashboardStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalProjects  int32                  `protobuf:"varint,1,opt,name=total_projects,json=totalProjects,proto3" json:"total_projects,omitempty"`
	ActiveProjects int32                  `protobuf:"varint,2,opt,name=active_projects,json=activeProjects,proto3" json:"active_projects,omitempty"`
	TotalTasks     int32                  `protobuf:"varint,3,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks int32                  `protobuf:"varint,4,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	PendingTasks   int32                  `protobuf:"varint,5,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	ProjectStats   []*ProjectStats        `protobuf:"bytes,6,rep,name=project_stats,json=projectStats,proto3" json:"project_stats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DashboardStatsResponse) Reset() {
	*x = DashboardStatsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardStatsResponse) ProtoMessage() {}

func (x *DashboardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardStatsResponse.ProtoReflect.Descriptor instead.
func (*DashboardStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *DashboardStatsResponse) GetTotalProjects() int32 {
	if x != nil {
		return x.TotalProjects
	}
	return 0
}

func (x *DashboardStatsResponse) GetActiveProjects() int32 {
	if x != nil {
		return x.ActiveProjects
	}
	return 0
}

func (x *DashboardStatsResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *DashboardStatsResponse) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *DashboardStatsResponse) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *DashboardStatsResponse) GetProjectStats() []*ProjectStats {
	if x != nil {
		return x.ProjectStats
	}
	return nil
}

var File_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/analytics/analytics.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\x8e\x01\n" +
	"\vProjectView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x127\n" +
	"\tviewed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bviewedAt\"R\n" +
	"\x18RecordProjectViewRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xa9\x01\n" +
	"\x16GetProjectViewsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"e\n" +
	"\x14ProjectViewsResponse\x12,\n" +
	"\x05views\x18\x01 \x03(\v2\x16.analytics.ProjectViewR\x05views\x12\x1f\n" +
	"\vtotal_views\x18\x02 \x01(\x05R\n" +
	"totalViews\"\xa3\x01\n" +
	"\fTaskActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x19RecordTaskActivityRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"R\n" +
	"\x18GetTaskActivitiesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\"Q\n" +
	"\x16TaskActivitiesResponse\x127\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x17.analytics.TaskActivityR\n" +
	"activities\"\xe1\x01\n" +
	"\fProjectStats\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x1f\n" +
	"\vtotal_tasks\x18\x02 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x03 \x01(\x05R\x0ecompletedTasks\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x01R\x0fprogressPercent\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"7\n" +
	"\x16GetProjectStatsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\"E\n" +
	"\x14ProjectStatsResponse\x12-\n" +
	"\x05stats\x18\x01 \x01(\v2\x17.analytics.ProjectStatsR\x05stats\"\x84\x01\n" +
	"\x19UpdateProjectStatsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x1f\n" +
	"\vtotal_tasks\x18\x02 \x01(\x03R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x03 \x01(\x03R\x0ecompletedTasks\"3\n" +
	"\x18GetDashboardStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x95\x02\n" +
	"\x16DashboardStatsResponse\x12%\n" +
	"\x0etotal_projects\x18\x01 \x01(\x05R\rtotalProjects\x12'\n" +
	"\x0factive_projects\x18\x02 \x01(\x05R\x0eactiveProjects\x12\x1f\n" +
	"\vtotal_tasks\x18\x03 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x04 \x01(\x05R\x0ecompletedTasks\x12#\n" +
	"\rpending_tasks\x18\x05 \x01(\x05R\fpendingTasks\x12<\n" +
	"\rproject_stats\x18\x06 \x03(\v2\x17.analytics.ProjectStatsR\fprojectStats2\xf1\x04\n" +
	"\x10AnalyticsService\x12J\n" +
	"\x11RecordProjectView\x12#.analytics.RecordProjectViewRequest\x1a\x10.analytics.Empty\x12U\n" +
	"\x0fGetProjectViews\x12!.analytics.GetProjectViewsRequest\x1a\x1f.analytics.ProjectViewsResponse\x12L\n" +
	"\x12RecordTaskActivity\x12$.analytics.RecordTaskActivityRequest\x1a\x10.analytics.Empty\x12[\n" +
	"\x11GetTaskActivities\x12#.analytics.GetTaskActivitiesRequest\x1a!.analytics.TaskActivitiesResponse\x12U\n" +
	"\x0fGetProjectStats\x12!.analytics.GetProjectStatsRequest\x1a\x1f.analytics.ProjectStatsResponse\x12[\n" +
	"\x12UpdateProjectStats\x12$.analytics.UpdateProjectStatsRequest\x1a\x1f.analytics.ProjectStatsResponse\x12[\n" +
	"\x11GetDashboardStats\x12#.analytics.GetDashboardStatsRequest\x1a!.analytics.DashboardStatsResponseB&Z$github.com/portfolio/proto/analyticsb\x06proto3"

var (
	file_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_analytics_proto_rawDescData []byte
)

func file_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_analytics_proto_rawDescData
}

var file_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_analytics_analytics_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: analytics.Empty
	(*ProjectView)(nil),               // 1: analytics.ProjectView
	(*RecordProjectViewRequest)(nil),  // 2: analytics.RecordProjectViewRequest
	(*GetProjectViewsRequest)(nil),    // 3: analytics.GetProjectViewsRequest
	(*ProjectViewsResponse)(nil),      // 4: analytics.ProjectViewsResponse
	(*TaskActivity)(nil),              // 5: analytics.TaskActivity
	(*RecordTaskActivityRequest)(nil), // 6: analytics.RecordTaskActivityRequest
	(*GetTaskActivitiesRequest)(nil),  // 7: analytics.GetTaskActivitiesRequest
	(*TaskActivitiesResponse)(nil),    // 8: analytics.TaskActivitiesResponse
	(*ProjectStats)(nil),              // 9: analytics.ProjectStats
	(*GetProjectStatsRequest)(nil),    // 10: analytics.GetProjectStatsRequest
	(*ProjectStatsResponse)(nil),      // 11: analytics.ProjectStatsResponse
	(*UpdateProjectStatsRequest)(nil), // 12: analytics.UpdateProjectStatsRequest
	(*GetDashboardStatsRequest)(nil),  // 13: analytics.GetDashboardStatsRequest
	(*DashboardStatsResponse)(nil),    // 14: analytics.DashboardStatsResponse
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_proto_analytics_analytics_proto_depIdxs = []int32{
	15, // 0: analytics.ProjectView.viewed_at:type_name -> google.protobuf.Timestamp
	15, // 1: analytics.GetProjectViewsRequest.start_date:type_name -> google.protobuf.Timestamp
	15, // 2: analytics.GetProjectViewsRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 3: analytics.ProjectViewsResponse.views:type_name -> analytics.ProjectView
	15, // 4: analytics.TaskActivity.created_at:type_name -> google.protobuf.Timestamp
	5,  // 5: analytics.TaskActivitiesResponse.activities:type_name -> analytics.TaskActivity
	15, // 6: analytics.ProjectStats.last_updated:type_name -> google.protobuf.Timestamp
	9,  // 7: analytics.ProjectStatsResponse.stats:type_name -> analytics.ProjectStats
	9,  // 8: analytics.DashboardStatsResponse.project_stats:type_name -> analytics.ProjectStats
	2,  // 9: analytics.AnalyticsService.RecordProjectView:input_type -> analytics.RecordProjectViewRequest
	3,  // 10: analytics.AnalyticsService.GetProjectViews:input_type -> analytics.GetProjectViewsRequest
	6,  // 11: analytics.AnalyticsService.RecordTaskActivity:input_type -> analytics.RecordTaskActivityRequest
	7,  // 12: analytics.AnalyticsService.GetTaskActivities:input_type -> analytics.GetTaskActivitiesRequest
	10, // 13: analytics.AnalyticsService.GetProjectStats:input_type -> analytics.GetProjectStatsRequest
	12, // 14: analytics.AnalyticsService.UpdateProjectStats:input_type -> analytics.UpdateProjectStatsRequest
	13, // 15: analytics.AnalyticsService.GetDashboardStats:input_type -> analytics.GetDashboardStatsRequest
	0,  // 16: analytics.AnalyticsService.RecordProjectView:output_type -> analytics.Empty
	4,  // 17: analytics.AnalyticsService.GetProjectViews:output_type -> analytics.ProjectViewsResponse
	0,  // 18: analytics.AnalyticsService.RecordTaskActivity:output_type -> analytics.Empty
	8,  // 19: analytics.AnalyticsService.GetTaskActivities:output_type -> analytics.TaskActivitiesResponse
	11, // 20: analytics.AnalyticsService.GetProjectStats:output_type -> analytics.ProjectStatsResponse
	11, // 21: analytics.AnalyticsService.UpdateProjectStats:output_type -> analytics.ProjectStatsResponse
	14, // 22: analytics.AnalyticsService.GetDashboardStats:output_type -> analytics.DashboardStatsResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_analytics_analytics_proto_init() }
func file_proto_analytics_analytics_proto_init() {
	if File_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_analytics_proto = out.File
	file_proto_analytics_analytics_proto_goTypes = nil
	file_proto_analytics_analytics_proto_depIdxs = nil
}
