// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/analytics/analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_RecordProjectView_FullMethodName  = "/analytics.AnalyticsService/RecordProjectView"
	AnalyticsService_GetProjectViews_FullMethodName    = "/analytics.AnalyticsService/GetProjectViews"
	AnalyticsService_RecordTaskActivity_FullMethodName = "/analytics.AnalyticsService/RecordTaskActivity"
	AnalyticsService_GetTaskActivities_FullMethodName  = "/analytics.AnalyticsService/GetTaskActivities"
	AnalyticsService_GetProjectStats_FullMethodName    = "/analytics.AnalyticsService/GetProjectStats"
	AnalyticsService_UpdateProjectStats_FullMethodName = "/analytics.AnalyticsService/UpdateProjectStats"
	AnalyticsService_GetDashboardStats_FullMethodName  = "/analytics.AnalyticsService/GetDashboardStats"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Analytics Service
type AnalyticsServiceClient interface {
	// Project Views
	RecordProjectView(ctx context.Context, in *RecordProjectViewRequest, opts ...grpc.CallOption) (*Empty, error)
	GetProjectViews(ctx context.Context, in *GetProjectViewsRequest, opts ...grpc.CallOption) (*ProjectViewsResponse, error)
	// Task Activity
	RecordTaskActivity(ctx context.Context, in *RecordTaskActivityRequest, opts ...grpc.CallOption) (*Empty, error)
	GetTaskActivities(ctx context.Context, in *GetTaskActivitiesRequest, opts ...grpc.CallOption) (*TaskActivitiesResponse, error)
	// Project Stats
	GetProjectStats(ctx context.Context, in *GetProjectStatsRequest, opts ...grpc.CallOption) (*ProjectStatsResponse, error)
	UpdateProjectStats(ctx context.Context, in *UpdateProjectStatsRequest, opts ...grpc.CallOption) (*ProjectStatsResponse, error)
	GetDashboardStats(ctx context.Context, in *GetDashboardStatsRequest, opts ...grpc.CallOption) (*DashboardStatsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) RecordProjectView(ctx context.Context, in *RecordProjectViewRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AnalyticsService_RecordProjectView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetProjectViews(ctx context.Context, in *GetProjectViewsRequest, opts ...grpc.CallOption) (*ProjectViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectViewsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetProjectViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) RecordTaskActivity(ctx context.Context, in *RecordTaskActivityRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AnalyticsService_RecordTaskActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTaskActivities(ctx context.Context, in *GetTaskActivitiesRequest, opts ...grpc.CallOption) (*TaskActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskActivitiesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTaskActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetProjectStats(ctx context.Context, in *GetProjectStatsRequest, opts ...grpc.CallOption) (*ProjectStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetProjectStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) UpdateProjectStats(ctx context.Context, in *UpdateProjectStatsRequest, opts ...grpc.CallOption) (*ProjectStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_UpdateProjectStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDashboardStats(ctx context.Context, in *GetDashboardStatsRequest, opts ...grpc.CallOption) (*DashboardStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDashboardStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// Analytics Service
type AnalyticsServiceServer interface {
	// Project Views
	RecordProjectView(context.Context, *RecordProjectViewRequest) (*Empty, error)
	GetProjectViews(context.Context, *GetProjectViewsRequest) (*ProjectViewsResponse, error)
	// Task Activity
	RecordTaskActivity(context.Context, *RecordTaskActivityRequest) (*Empty, error)
	GetTaskActivities(context.Context, *GetTaskActivitiesRequest) (*TaskActivitiesResponse, error)
	// Project Stats
	GetProjectStats(context.Context, *GetProjectStatsRequest) (*ProjectStatsResponse, error)
	UpdateProjectStats(context.Context, *UpdateProjectStatsRequest) (*ProjectStatsResponse, error)
	GetDashboardStats(context.Context, *GetDashboardStatsRequest) (*DashboardStatsResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) RecordProjectView(context.Context, *RecordProjectViewRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordProjectView not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetProjectViews(context.Context, *GetProjectViewsRequest) (*ProjectViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectViews not implemented")
}
func (UnimplementedAnalyticsServiceServer) RecordTaskActivity(context.Context, *RecordTaskActivityRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordTaskActivity not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTaskActivities(context.Context, *GetTaskActivitiesRequest) (*TaskActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskActivities not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetProjectStats(context.Context, *GetProjectStatsRequest) (*ProjectStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) UpdateProjectStats(context.Context, *UpdateProjectStatsRequest) (*ProjectStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDashboardStats(context.Context, *GetDashboardStatsRequest) (*DashboardStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_RecordProjectView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordProjectViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).RecordProjectView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_RecordProjectView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).RecordProjectView(ctx, req.(*RecordProjectViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetProjectViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetProjectViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetProjectViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetProjectViews(ctx, req.(*GetProjectViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_RecordTaskActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordTaskActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).RecordTaskActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_RecordTaskActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).RecordTaskActivity(ctx, req.(*RecordTaskActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTaskActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTaskActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTaskActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTaskActivities(ctx, req.(*GetTaskActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetProjectStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetProjectStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetProjectStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetProjectStats(ctx, req.(*GetProjectStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_UpdateProjectStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).UpdateProjectStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_UpdateProjectStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).UpdateProjectStats(ctx, req.(*UpdateProjectStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDashboardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDashboardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDashboardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDashboardStats(ctx, req.(*GetDashboardStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordProjectView",
			Handler:    _AnalyticsService_RecordProjectView_Handler,
		},
		{
			MethodName: "GetProjectViews",
			Handler:    _AnalyticsService_GetProjectViews_Handler,
		},
		{
			MethodName: "RecordTaskActivity",
			Handler:    _AnalyticsService_RecordTaskActivity_Handler,
		},
		{
			MethodName: "GetTaskActivities",
			Handler:    _AnalyticsService_GetTaskActivities_Handler,
		},
		{
			MethodName: "GetProjectStats",
			Handler:    _AnalyticsService_GetProjectStats_Handler,
		},
		{
			MethodName: "UpdateProjectStats",
			Handler:    _AnalyticsService_UpdateProjectStats_Handler,
		},
		{
			MethodName: "GetDashboardStats",
			Handler:    _AnalyticsService_GetDashboardStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytics/analytics.proto",
}
